# ANDRES PLAYGROUND

In [7]:
%%time
import pandas as pd
import glob

path = r'annualData2014-2019/' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    temp_df = pd.read_csv(filename, index_col=None, header=0)
    li.append(temp_df)

df = pd.concat(li, axis=0, ignore_index=True)
df.head(20)

<string>:2: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.

CPU times: user 1.39 s, sys: 73.3 ms, total: 1.46 s
Wall time: 1.48 s

,X,Y,OBJECTID,RADICADO,FECHA,HORA,DIA,PERIODO,CLASE,DIRECCION,...,COMUNA,DISENO,DIA_NOMBRE,MES,MES_NOMBRE,X_MAGNAMED,Y_MAGNAMED,LONGITUD,LATITUD,SHAPE
0,-75.602726,6.219016,211279,1423828,2014/01/01 00:00:00+00,02:20:00,1,2014,Choque,CR 80 CL 8,...,Belén,Tramo de via,MIÉRCOLES,1,NaN,831190.08,1179689.50,-75.602726,6.219016,NaN
1,-75.568185,6.260009,211280,1423839,2014/01/01 00:00:00+00,12:50:00,1,2014,Atropello,CR 53 CL 61,...,La Candelaria,Tramo de via,MIÉRCOLES,1,NaN,835013.63,1184223.79,-75.568185,6.260009,NaN
2,-75.549943,6.264765,211281,1423840,2014/01/01 00:00:00+00,01:00:00,1,2014,Atropello,CR 39 CL 70,...,Manrique,Tramo de via,MIÉRCOLES,1,NaN,837032.71,1184749.86,-75.549943,6.264765,NaN
3,-75.607611,6.234327,211282,1423849,2014/01/01 00:00:00+00,12:37:00,1,2014,Atropello,CL 32 CR 84,...,Belén,Tramo de via,MIÉRCOLES,1,NaN,830649.47,1181383.24,-75.607611,6.234327,NaN
4,-75.579685,6.299968,211283,1423890,2014/01/01 00:00:00+00,10:40:00,1,2014,Caída de Ocupante,CR 80 CL 101,...,Doce de Octubre,Tramo de via,MIÉRCOLES,1,NaN,833740.78,1188643.80,-75.579685,6.299968,NaN
5,-75.555429,6.284499,211284,1423892,2014/01/01 00:00:00+00,04:00:00,1,2014,Choque,CR 48 CL 93,...,Aranjuez,Interseccion,MIÉRCOLES,1,NaN,836425.43,1186932.72,-75.555429,6.284499,NaN
6,-75.555254,6.243999,211285,1423894,2014/01/01 00:00:00+00,07:15:00,1,2014,Choque,CL 51 CR 35,...,Buenos Aires,Tramo de via,MIÉRCOLES,1,NaN,836444.97,1182452.83,-75.555254,6.243999,NaN
7,-75.554608,6.235756,211286,1423896,2014/01/01 00:00:00+00,05:00:00,1,2014,Choque,CR 29 CL 42,...,Buenos Aires,Interseccion,MIÉRCOLES,1,NaN,836516.47,1181541.10,-75.554608,6.235756,NaN
8,-75.595777,6.257979,211287,1423897,2014/01/01 00:00:00+00,01:30:00,1,2014,Choque,CR 78 CL 47 D,...,Laureles Estadio,Tramo de via,MIÉRCOLES,1,NaN,831959.55,1183999.31,-75.595777,6.257979,NaN
9,-75.576781,6.220072,211288,1423898,2014/01/01 00:00:00+00,02:00:00,1,2014,Caída de Ocupante,CR 49 CL 18,...,El Poblado,Tramo de via,MIÉRCOLES,1,NaN,834062.02,1179806.22,-75.576781,6.220072,NaN
10,-75.558562,6.273590,211290,1423900,2014/01/01 00:00:00+00,06:10:00,1,2014,Choque,CR 49 A CL 80,...,Aranjuez,Tramo de via,MIÉRCOLES,1,NaN,836078.72,1185726.03,-75.558562,6.273590,NaN
11,-75.545969,6.280562,211291,1423902,2014/01/01 00:00:00+00,11:30:00,1,2014,Atropello,CR 36 CL 86,...,Manrique,Tramo de via,MIÉRCOLES,1,NaN,837472.49,1186497.30,-75.545969,6.280562,NaN
12,-75.573364,6.276299,211292,1423904,2014/01/01 00:00:00+00,05:55:00,1,2014,Otro,CR 65 CL 80,...,Castilla,Tramo de via,MIÉRCOLES,1,NaN,834440.37,1186025.73,-75.573364,6.276299,NaN
13,-75.549609,6.270232,211293,1423906,2014/01/01 00:00:00+00,07:20:00,1,2014,Choque,CR 40 CL 78,...,Manrique,Tramo de via,MIÉRCOLES,1,NaN,837069.65,1185354.59,-75.549609,6.270232,NaN
14,-75.547123,6.298778,211294,1423909,2014/01/01 00:00:00+00,04:00:00,1,2014,Atropello,CL 110 A CR 42 C,...,Popular,Tramo de via,MIÉRCOLES,1,NaN,837344.78,1188512.18,-75.547123,6.298778,NaN
15,-75.543289,6.269559,211295,1423911,2014/01/01 00:00:00+00,11:00:00,1,2014,Caída de Ocupante,CR 30 CL 78,...,Manrique,Tramo de via,MIÉRCOLES,1,NaN,837769.15,1185280.20,-75.543289,6.269559,NaN
16,-75.592028,6.281756,211296,1423912,2014/01/01 00:00:00+00,01:20:00,1,2014,Choque,CR 86 C CL 76 DD,...,Robledo,Tramo de via,MIÉRCOLES,1,NaN,832374.61,1186629.33,-75.592028,6.281756,NaN
17,-75.545051,6.288367,211297,1423915,2014/01/01 00:00:00+00,12:30:00,1,2014,Choque,CR 35 B CL 99,...,Popular,Tramo de via,MIÉRCOLES,1,NaN,837574.09,1187360.61,-75.545051,6.288367,NaN
18,-75.594979,6.281063,211298,1423916,2014/01/01 00:00:00+00,03:30:00,1,2014,Otro,CR 89 CL 76,...,Robledo,Tramo de via,MIÉRCOLES,1,NaN,832048.05,1186552.76,-75.594979,6.281063,NaN
19,-75.643857,6.178138,211299,1423918,2014/01/01 00:00:00+00,04:45:00,1,2014,Caída de Ocupante,CR 63 CL 49 B Sur,...,Corregimiento de San Antonio de Prado,Tramo de via,MIÉRCOLES,1,NaN,826636.36,1175168.44,-75.643857,6.178138,NaN

In [8]:
df.describe()

,X,Y,OBJECTID,DIA,PERIODO,MES,X_MAGNAMED,Y_MAGNAMED,LONGITUD,LATITUD,SHAPE
count,240333.000000,240333.000000,251899.000000,251899.000000,251899.000000,251899.000000,251899.000000,2.518990e+05,251899.000000,251899.000000,0.0
mean,-75.576792,6.250698,407060.003684,15.668522,2016.497858,6.628601,834066.272241,1.183194e+06,-75.576743,6.250699,NaN
std,0.018724,0.027988,245243.193626,8.736602,1.704951,3.401817,2072.292554,3.093639e+03,0.018722,0.027968,NaN
min,-75.701661,6.151932,1.000000,1.000000,2014.000000,1.000000,820242.740000,1.172269e+06,-75.701661,6.151932,NaN
25%,-75.586662,6.232658,234384.500000,8.000000,2015.000000,4.000000,832979.740000,1.181198e+06,-75.586561,6.232651,NaN
50%,-75.574753,6.250417,346018.000000,16.000000,2016.000000,7.000000,834292.800000,1.183163e+06,-75.574697,6.250417,NaN
75%,-75.565067,6.271445,664807.500000,23.000000,2018.000000,10.000000,835367.280000,1.185485e+06,-75.564990,6.271408,NaN
max,-75.473437,6.368394,758669.000000,31.000000,2019.000000,12.000000,845502.630000,1.196215e+06,-75.473437,6.368394,NaN